version: '3'
services:
#  app:
#    image: stavshamir/springwolf-cloud-stream-rabbit-binder-example:0.3.1
#    links:
#      - rabbit
#    ports:
#      - "8080:8080"
#    depends_on:
#      - rabbit

  rabbit:
    image: rabbitmq:3.8-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

